package com.fineinsight.zzango.questionnaire.DataClass

import java.io.Serializable

data class ServerPaper_Cancer (
    var c_date:String,
    var c_bun:String,
    var c_year:String,
    var c_email:String,
    var c_jungyn:String,
    var ck1 :String,
    var ck1_1 :String,
    var ck2:String,
    var ck2_1:String,
    var ck3_1:String,
    var ck3_1_1:String,
    var ck3_1_2:String,
    var ck3_1_3:String,
    var ck3_1_4:String,
    var ck3_1_5:String,
    var ck3_2:String,
    var ck3_2_1:String,
    var ck3_2_2:String,
    var ck3_2_3:String,
    var ck3_2_4:String,
    var ck3_2_5:String,
    var ck3_3:String,
    var ck3_3_1:String,
    var ck3_3_2:String,
    var ck3_3_3:String,
    var ck3_3_4:String,
    var ck3_3_5:String,
    var ck3_4:String,
    var ck3_4_1:String,
    var ck3_4_2:String,
    var ck3_4_3:String,
    var ck3_4_4:String,
    var ck3_4_5:String,
    var ck3_5:String,
    var ck3_5_1:String,
    var ck3_5_2:String,
    var ck3_5_3:String,
    var ck3_5_4:String,
    var ck3_5_5:String,
    var ck3_6:String,
    var ck3_6_1:String,
    var ck3_6_2:String,
    var ck3_6_3:String,
    var ck3_6_4:String,
    var ck3_6_5:String,
    var ck3_6_kita:String,
    var ck4_1:String,
    var ck4_2:String,
    var ck4_3:String,
    var ck4_4:String,
    var ck4_5:String,
    var ck4_6:String,
    var ck4_7:String,
    var ck4_8:String,
    var ck4_9:String,
    var ck5_1:String,
    var ck5_2:String,
    var ck5_3:String,
    var ck5_4:String,
    var ck5_5:String,
    var ck6_1:String,
    var ck6_2:String,
    var ck6_3:String,
    var ck6_4:String,
    var ck6_5:String,
    var ck7_1:String,
    var ck7_2:String,
    var ck7_3:String,
    var ck7_4:String,
    var ck7_5:String,
    var ck8_1 :String,
    var ck8_2 :String,
    var ck9_1 :String,
    var ck9_2 :String,
    var ck10 :String,
    var ck11 :String,
    var ck12 :String,
    var ck13 :String,
    var ck14 :String,
    var ck15_5 :String,
    var ck15_5_1 :String,
    var ck15_5_2 :String,
    var ck15_5_3 :String,
    var ck15_5_4 :String,
    var ck15_5_5 :String,
    var ck16_1 :String,
    var ck16_2 :String,
    var ck16_3 :String,
    var ck16_4 :String,
    var ck16_5 :String,
    var ck16_6 :String,
    var c_name:String,
    var c_jumin:String
):Serializable