package com.example.zzango.questionnaire.LocalList

import java.io.Serializable

//로컬 저장 리스트
data class Paper(var isChecked: Boolean, var no: String, var category: String, var name: String) : Serializable

//구강검진 리스트
data class Paper_ORAL(
var exam_date:String,
var no:String,
var name:String,
var first_serial:String,
var last_serial:String,
var category:String,
var oral_1 :String,
var oral_2 :String,
var oral_3 :String,
var oral_4 :String,
var oral_5 :String,
var oral_6 :String,
var oral_7 :String,
var oral_8 :String,
var oral_9 :String,
var oral_10:String,
var oral_11:String,
var oral_12:String,
var oral_13:String,
var oral_14:String,
var oral_15:String,
var remark :String
): Serializable


data class Paper_COMMON(

var exam_date:String,
var no :String,
var name :String,
var first_serial:String,
var last_serial:String,
var category:String,
var mj1_1_1:String,
var mj1_1_2:String,
var mj1_2_1:String,
var mj1_2_2:String,
var mj1_3_1:String,
var mj1_3_2:String,
var mj1_4_1:String,
var mj1_4_2:String,
var mj1_5_1:String,
var mj1_5_2:String,
var mj1_6_1:String,
var mj1_6_2:String,
var mj1_7_1:String,
var mj1_7_2:String,
var mj1_7_etc:String,
var mj2_1:String,
var mj2_2 :String,
var mj2_3 :String,
var mj2_4 :String,
var mj2_5 :String,
var mj3:String,
var mj4:String,
var mj4_1_1:String,
var mj4_1_2:String,
var mj4_2_1:String,
var mj4_2_2:String,
var mj4_2_3:String,
var mj5:String,
var mj5_1_1:String,
var mj5_1_2:String,
var mj5_2_1:String,
var mj5_2_2:String,
var mj5_2_3:String,
var mj6:String,
var mj6_1:String,
var mj71 :String,
var mj72:String,
var mj73:String,
var mj74 :String,
var mj7_1_11:String,
var mj7_1_12:String,
var mj7_1_13:String,
var mj7_1_14:String,
var mj7_1_21:String,
var mj7_1_22:String,
var mj7_1_23:String,
var mj7_1_24:String,
var mj7_1_31:String,
var mj7_1_32:String,
var mj7_1_33:String,
var mj7_1_34:String,
var mj7_1_41:String,
var mj7_1_42:String,
var mj7_1_43:String,
var mj7_1_44:String,
var mj7_1_51:String,
var mj7_1_52:String,
var mj7_1_53:String,
var mj7_1_54:String,
var mj7_1_etc:String,
var mj7_2_11 :String,
var mj7_2_12 :String,
var mj7_2_13 :String,
var mj7_2_14 :String,
var mj7_2_21 :String,
var mj7_2_22 :String,
var mj7_2_23 :String,
var mj7_2_24 :String,
var mj7_2_31 :String,
var mj7_2_32 :String,
var mj7_2_33 :String,
var mj7_2_34 :String,
var mj7_2_41 :String,
var mj7_2_42 :String,
var mj7_2_43 :String,
var mj7_2_44 :String,
var mj7_2_51 :String,
var mj7_2_52 :String,
var mj7_2_53 :String,
var mj7_2_54 :String,
var mj7_2_etc:String,
var mj8_1:String,
var mj8_2_1:String,
var mj8_2_2 :String,
var mj9_1:String,
var mj9_2_1 :String,
var mj9_2_2 :String,
var mj10:String
):Serializable



data class Paper_MENTAL(
var exam_date:String,
var no:String,
var name:String,
var first_serial:String,
var last_serial :String,
var category :String,
var mj_mtl_1 :String,
var mj_mtl_2 :String,
var mj_mtl_3 :String,
var mj_mtl_4 :String,
var mj_mtl_5 :String,
var mj_mtl_6 :String,
var mj_mtl_7 :String,
var mj_mtl_8 :String,
var mj_mtl_9 :String,
var mj_mtl_sum :String
):Serializable

data class Paper_COGNITIVE(
var exam_date :String,
var no :String,
var name :String,
var first_serial :String,
var last_serial :String,
var category :String,
var mj_inji_1 :String,
var mj_inji_2 :String,
var mj_inji_3 :String,
var mj_inji_4 :String,
var mj_inji_5 :String,
var mj_inji_6 :String,
var mj_inji_7 :String,
var mj_inji_8 :String,
var mj_inji_9 :String,
var mj_inji_10 :String,
var mj_inji_11 :String,
var mj_inji_12 :String,
var mj_inji_13 :String,
var mj_inji_14 :String,
var mj_inji_15 :String,
var mj_inji_sum :String
):Serializable

data class Paper_ELDERLY(

var exam_date:String,
var no :String,
var name :String,
var first_serial:String,
var last_serial :String,
var category :String,
var mj66_1 :String,
var mj66_2 :String,
var mj66_3_1:String,
var mj66_3_2:String,
var mj66_3_3:String,
var mj66_3_4:String,
var mj66_3_5:String,
var mj66_3_6:String,
var mj66_4 :String,
var mj66_5 :String
):Serializable